#ifndef _opcodes_h
#define _opcodes_h

typedef enum {
    INC_REGISTER,
    DEC_REGISTER,
    ADD_VALUE_REGISTER,
    SUB_VALUE_REGISTER,
    MUL_VALUE_REGISTER,
    DIV_VALUE_REGISTER,
    MOV_VALUE_REGISTER,
    MOV_ADDRESS_REGISTER,
    SHIFT_LEFT_BITS_REGISTER,
    SHIFT_RIGHT_BITS_REGISTER,
    LOGICAL_AND_BITS_REGISTER,
    LOGICAL_NOT_REGISTER,
    LOGICAL_XOR_REGISTER,

    INC_ADDRESS,
    DEC_ADDRESS,
    ADD_VALUE_ADDRESS,
    SUB_VALUE_ADDRESS,
    MUL_VALUE_ADDRESS,
    DIV_VALUE_ADDRESS,
    MOV_VALUE_ADDRESS,
    MOV_REGISTER_ADDRESS,
    SHIFT_LEFT_BITS_ADDRESS,
    SHIFT_RIGHT_BITS_ADDRESS,
    LOGICAL_AND_BITS_ADDRESS,
    LOGICAL_NOT_ADDRESS,
    LOGICAL_XOR_ADDRESS,

    COMPARE_REGISTER_REGISTER,
    JUMP_IF_EQUAL_LABEL,
    JUMP_IF_NOT_EQUAL_LABEL,
    JUMP_IF_LESS_THAN_LABEL,
    JUMP_IF_GREATER_THAN_LABEL,
    JUMP_TO_LABEL,
    DEFINE_LABEL,

    PUSH_REGISTER,
    POP_REGISTER,
    
    INTERRUPT_INTERRUPT_CODE
} Opcodes_T;

#endif